-- ============================================================================
-- SwapDoor — CMS schema (blog posts + editable site sections)
--
-- Run once in Supabase: Dashboard -> SQL Editor -> paste -> Run.
-- Safe to re-run: everything is IF NOT EXISTS / CREATE OR REPLACE / DROP-then-
-- CREATE, matching the style of schema.sql.
--
-- This is the half of the "remote headless CMS" requirement (Overview §5) that
-- was still missing. `houses` has been served from Supabase since 2026-08-17,
-- but the blog and the whole How-it-Works page were hardcoded in .tsx files —
-- changing one FAQ answer meant an edit and a deploy. After this migration both
-- live in the database, RLS decides who may write, and /admin is the editor.
--
-- Content seed lives in supabase/seed-cms.sql (generated from lib/cms-seed.json
-- by scripts/build-cms-seed.mjs). Run this file first, then that one.
-- ============================================================================


-- ---------------------------------------------------------------------------
-- 1. Roles
--
-- One extra column rather than a separate table: there are exactly two roles
-- and no per-resource permissions, so a join table would be ceremony. If a
-- third role ever appears with different rights, that is when it earns a table.
-- ---------------------------------------------------------------------------
alter table public.profiles
  add column if not exists role text not null default 'member';

do $$
begin
  alter table public.profiles
    add constraint profiles_role_check check (role in ('member', 'admin'));
exception
  when duplicate_object then null;
end $$;

comment on column public.profiles.role is
  'member (default) or admin. Admins may write blog_posts and site_content. '
  'Only an admin can change this column — enforced by profiles_guard_role below.';


-- Is the CALLER an admin? Used by every write policy in this file.
--
-- SECURITY DEFINER so the lookup is not itself filtered by the RLS policies on
-- `profiles`, and `search_path` is pinned so the function cannot be redirected
-- by a caller-set path.
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and role = 'admin'
  );
$$;

revoke execute on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated, anon;


-- ---------------------------------------------------------------------------
-- 2. Close the privilege-escalation hole that adding `role` opens
--
-- schema.sql already ships "Users can update their own profile", a policy whose
-- USING/WITH CHECK is `auth.uid() = id` — i.e. a member may update ANY column
-- of their own row. The moment `role` exists on that row, that policy lets any
-- signed-in member run
--
--     update profiles set role = 'admin' where id = auth.uid();
--
-- and grant themselves the CMS. RLS cannot express "every column except this
-- one", so the guard is a trigger: the value may only change when the caller is
-- already an admin. Adding the column without this trigger would make the whole
-- rest of the file decorative.
-- ---------------------------------------------------------------------------
create or replace function public.guard_profile_role()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.role is distinct from old.role and not public.is_admin() then
    raise exception 'Only an admin can change a profile role'
      using errcode = 'insufficient_privilege';
  end if;
  return new;
end;
$$;

drop trigger if exists profiles_guard_role on public.profiles;
create trigger profiles_guard_role
  before update on public.profiles
  for each row
  execute function public.guard_profile_role();


-- ---------------------------------------------------------------------------
-- 3. blog_posts
--
-- `content` is jsonb: an ordered array of typed blocks (paragraph, heading,
-- image, gallery, quote, callout, video, code, listing) whose shapes are the
-- `Block` union in lib/cms-types.ts. Keeping it as jsonb rather than as a
-- block table is deliberate — a post is always read whole, never queried
-- block-by-block, so a join per paragraph would buy nothing.
-- ---------------------------------------------------------------------------
create table if not exists public.blog_posts (
  id           bigint generated by default as identity primary key,
  slug         text not null unique,
  title        text not null,
  excerpt      text not null default '',
  cover        text not null default '',
  category     text not null default 'travel'
                 check (category in ('travel', 'hosting', 'trust', 'guides')),
  -- The author as a member, when the post is written by one. ON DELETE SET NULL
  -- so deleting an account never deletes published editorial; `author_name`
  -- keeps the byline readable in that case.
  author_id    uuid references public.profiles(id) on delete set null,
  author_name  text,
  status       text not null default 'draft'
                 check (status in ('draft', 'published')),
  published_at timestamptz,
  read_minutes integer not null default 1,
  content      jsonb not null default '[]'::jsonb,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

comment on table public.blog_posts is
  'Public blog. Read by /blog and /blog/[slug]; written only from /admin.';
comment on column public.blog_posts.content is
  'Ordered array of typed blocks — see the Block union in lib/cms-types.ts.';

-- The list page reads published posts newest-first; the index makes that an
-- index scan rather than a sort over the table.
create index if not exists blog_posts_published_idx
  on public.blog_posts (status, published_at desc);

alter table public.blog_posts enable row level security;

-- Public read, but ONLY of published rows. A draft is invisible to anonymous
-- and signed-in members alike; admins see everything so /admin can list drafts.
drop policy if exists "Published posts are viewable by everyone" on public.blog_posts;
create policy "Published posts are viewable by everyone"
  on public.blog_posts for select
  using (status = 'published' or public.is_admin());

drop policy if exists "Admins can create posts" on public.blog_posts;
create policy "Admins can create posts"
  on public.blog_posts for insert
  with check (public.is_admin());

drop policy if exists "Admins can update posts" on public.blog_posts;
create policy "Admins can update posts"
  on public.blog_posts for update
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists "Admins can delete posts" on public.blog_posts;
create policy "Admins can delete posts"
  on public.blog_posts for delete
  using (public.is_admin());


-- ---------------------------------------------------------------------------
-- 4. site_content
--
-- A tiny key/value store for the editable prose that is not a blog post — today
-- the four sections of /how-it-works. A key is a plain string
-- ('how_it_works.faq'), so adding a section later is a constant in
-- lib/cms-types.ts rather than a migration.
--
-- Note what is NOT in here: the layout. An editor changes the words, the order
-- and which product panel a step shows; they cannot change how the page is
-- built. That boundary is what keeps every page on the design system.
-- ---------------------------------------------------------------------------
create table if not exists public.site_content (
  key        text primary key,
  value      jsonb not null,
  updated_at timestamptz not null default now(),
  updated_by uuid references public.profiles(id) on delete set null
);

comment on table public.site_content is
  'Editable page sections keyed by string (e.g. how_it_works.faq). Values are '
  'jsonb matching the types in lib/cms-types.ts.';

alter table public.site_content enable row level security;

drop policy if exists "Site content is viewable by everyone" on public.site_content;
create policy "Site content is viewable by everyone"
  on public.site_content for select
  using (true);

drop policy if exists "Admins can write site content" on public.site_content;
create policy "Admins can write site content"
  on public.site_content for insert
  with check (public.is_admin());

drop policy if exists "Admins can update site content" on public.site_content;
create policy "Admins can update site content"
  on public.site_content for update
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists "Admins can delete site content" on public.site_content;
create policy "Admins can delete site content"
  on public.site_content for delete
  using (public.is_admin());


-- ---------------------------------------------------------------------------
-- 5. updated_at, kept honest by the database
--
-- The admin form could set it, but then a row edited any other way (psql, the
-- Table Editor) would silently lie about when it changed.
-- ---------------------------------------------------------------------------
create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists blog_posts_touch on public.blog_posts;
create trigger blog_posts_touch
  before update on public.blog_posts
  for each row
  execute function public.touch_updated_at();

drop trigger if exists site_content_touch on public.site_content;
create trigger site_content_touch
  before update on public.site_content
  for each row
  execute function public.touch_updated_at();


-- ---------------------------------------------------------------------------
-- 6. Publishing stamps its own date
--
-- `published_at` drives the ordering of /blog and the dateline on a post, so it
-- must be set exactly when a draft first goes live — and must NOT move when a
-- published post is later corrected for a typo.
-- ---------------------------------------------------------------------------
create or replace function public.stamp_published_at()
returns trigger
language plpgsql
as $$
begin
  if new.status = 'published' and new.published_at is null then
    new.published_at = now();
  end if;
  return new;
end;
$$;

drop trigger if exists blog_posts_stamp_published on public.blog_posts;
create trigger blog_posts_stamp_published
  before insert or update on public.blog_posts
  for each row
  execute function public.stamp_published_at();
